
INSERT INTO person
(
person_id
,first_name
,last_name
)
VALUES
('Sample-personId0','Sample-firstName0','Sample-lastName0')
,
('Sample-personId1','Sample-firstName1','Sample-lastName1')
;

INSERT INTO ITEM_ATTR_TYPE_DATATYPE(
  ITEM_ATTR_TYPE_DATATYPE_ID,
  ITEM_ATTR_TYPE_DATATYPE_NAME,
  ITEM_ATTR_TYPE_DATATYPE_DESC,
  REGEX_PATTERN
)
VALUES
(1, 'STRING','STRING', ''),
(2, 'NUMBER','NUMBER', '')
;


INSERT INTO ITEM_TYPE(ITEM_TYPE_ID, ITEM_TYPE_CODE, ITEM_TYPE_NAME, ITEM_TYPE_DESC)
VALUES
('001','PERSON', 'Person', 'Person Entity'),
('002','COMPANY', 'Company', 'Company Entity');


INSERT INTO ITEM_ATTRIBUTE_TYPE(
  ITEM_ATTR_TYPE_ID,  ITEM_ATTR_TYPE_CODE,
  ITEM_ATTR_TYPE_NAME,  ITEM_ATTR_TYPE_DESC,
  ITEM_ATTR_TYPE_DATATYPE_ID, ITEM_ATTR_TYPE_LENGTH,
  ITEM_ATTR_TYPE_ISSEARCHABLE,  ITEM_ATTR_TYPE_DISPLAY_INDEX,
  ITEM_ATTR_TYPE_IS_REQUIRED,  ITEM_ATTR_TYPE_IS_METAPHONEKEY,
  ITEM_ATTR_TYPE_METAPHONEKEYPOS,  ITEM_ATTR_TYPE_LOOKUP_LIST_ID,
  ITEM_TYPE_ID
)
VALUES(
  '00001', 'FIRST_NAME', 
  'First Name', 'First Name',
  1, 30,
  1, 1,
  0, 0,
  1, NULL,
  '001'
)
;

